# Generated by Django 3.2.2 on 2021-07-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=950),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
